### ISSUE TITLE
feedback on version 0.4.0 - works great

### ISSUE THREAD

**Issue by m040601** [techknowlogick/shiori#124]
On ArchLinux with your compiled v 0.4.0 for 64bit,everything seems to work, except for browsing  by tags. That is:
- on the main window, clicking on some random tag doest do anything
- clicking on "show tags" the "existing tags" popup opens but the the tags are not clickable

I've tried different browsers, disabling all the blockers and fresh profiles.Here is what I got as error messages (not a developer so bare with me if something is missing):

- from Firefox's javascript console:

`
ReferenceError: "assignment to undeclared variable rxTag"
filterTag http://localhost:8080/dist/src.2748baec.js:31 
click http://localhost:8080/dist/src.2748baec.js line 3 > Function:3 
Be http://localhost:8080/dist/src.2748baec.js:3 
n http://localhost:8080/dist/src.2748baec.js:3 
_wrapper http://localhost:8080/dist/src.2748baec.js:3 
src.2748baec.js:3:11500
    ze http://localhost:8080/dist/src.2748baec.js:3 
Ue http://localhost:8080/dist/src.2748baec.js:3 
He http://localhost:8080/dist/src.2748baec.js:3 
Be http://localhost:8080/dist/src.2748baec.js:3 
n http://localhost:8080/dist/src.2748baec.js:3 
_wrapper http://localhost:8080/dist/src.2748baec.js:3 
`

and

`
Source map error: ReferenceError: WebAssembly is not defined
Resource URL: http://localhost:8080/dist/src.2748baec.js
Source Map URL: /dist/src.2748baec.map[Learn More] 
`

- from Qutebrowser inspector:

`
vue.common.prod.js:6 ReferenceError: rxTag is not defined
    at wn.filterTag (index.js:187)
    at click (eval at Ya (vue.common.prod.js:6), <anonymous>:3:5880)
    at Be (vue.common.prod.js:6)
    at HTMLAnchorElement.n (vue.common.prod.js:6)
    at HTMLAnchorElement.Yr.o._wrapper (vue.common.prod.js:6)
ze	@	vue.common.prod.js:6
Ue	@	vue.common.prod.js:6
He	@	vue.common.prod.js:6
Be	@	vue.common.prod.js:6
n	@	vue.common.prod.js:6
Yr.o._wrapper	@	vue.common.prod.js:6
`

and

`
vue.common.prod.js:6 ReferenceError: rxTag is not defined
    at wn.filterTag (index.js:187)
    at click (eval at Ya (vue.common.prod.js:6), <anonymous>:3:9120)
    at Be (vue.common.prod.js:6)
    at HTMLAnchorElement.n (vue.common.prod.js:6)
    at HTMLAnchorElement.Yr.o._wrapper (vue.common.prod.js:6)
ze	@	vue.common.prod.js:6
Ue	@	vue.common.prod.js:6
He	@	vue.common.prod.js:6
Be	@	vue.common.prod.js:6
n	@	vue.common.prod.js:6
Yr.o._wrapper	@	vue.common.prod.js:6
﻿`

**Comment by techknowlogick** [comment]
Thanks for feedback, I expect this might be caused by the minification of JavaScript. I will attempt to replicate and provide a fix.

**Comment by techknowlogick** [comment]
@m040601 I've published nightly builds (based off of latest commit to master branch) here: https://dl.techknowlogick.com/shiori/nightly/ could you try and see if the parcel upgrade solved your problem?

**Comment by m040601** [comment]
no, still getting this error message

qutebrowser:
```
ReferenceError: rxTag is not defined
    at wn.filterTag (index.js:187)
    at click (eval at Ya (vue.common.prod.js:6), <anonymous>:3:5880)
    at Be (vue.common.prod.js:6)
    at HTMLAnchorElement.n (vue.common.prod.js:6)
    at HTMLAnchorElement.Yr.o._wrapper (vue.common.prod.js:6)
ze	@	vue.common.prod.js:6
Ue	@	vue.common.prod.js:6
He	@	vue.common.prod.js:6
Be	@	vue.common.prod.js:6
n	@	vue.common.prod.js:6
Yr.o._wrapper	@	vue.common.prod.js:6
```


firefox:
```

ReferenceError: "assignment to undeclared variable rxTag"
    filterTag http://localhost:8080/dist/src.4ae0c97b.js:31 click http://localhost:8080/dist/src.4ae0c97b.js line 3 > Function:3 Be http://localhost:8080/dist/src.4ae0c97b.js:3 n http://localhost:8080/dist/src.4ae0c97b.js:3 _wrapper http://localhost:8080/dist/src.4ae0c97b.js:3 
src.4ae0c97b.js:3:11500
Source map error: ReferenceError: WebAssembly is not defined
Resource URL: http://localhost:8080/dist/src.4ae0c97b.js
Source Map URL: /dist/src.4ae0c97b.js.map[Learn More]
```



by the way, could you guys add a "-version" switch to shiroi ?
Really helpful and essential, if you're releasing binary packages on a Linux Distro

**Comment by techknowlogick** [comment]
@m040601 I was able to trace down the error. Your error log was very helpful, I've pushed a fix for it.

I've also created an issue to add the -version flag

**Comment by m040601** [comment]
Great job !
It works !
By the way, this, https://dl.techknowlogick.com/shiori/ where you release your "nightly" "unstable" "testing" versions is really usefull. Clarify it better for (less technical) users on the front page:
- that it's a Go binary, it works in Windows, Linux, Mac etc ...
- that it's portable and self sufficient, they dont' need to worry about installing anything else
- that they have 2 options for downloading:
  - a stable one, https://github.com/techknowlogick/shiori/releases
  - a nightly one, https://dl.techknowlogick.com/shiori/ , that changes very often and is useful   for helping testing.
- that when they report an issue, dont' forget to mention which version  they're using.
